### ISSUE TITLE
Recover fix_archive bot

### ISSUE THREAD

**Issue by Nirvanchik** [Nirvanchik/nirvana-bot#81]
1) Rename bot: archvie -> fix_archive
2) Fix exception:
Exception in thread "main" java.lang.NullPointerException
        at org.wikipedia.nirvana.archive.NirvanaArchiveBot.updateAllArchives(NirvanaArchiveBot.java:232)
        at org.wikipedia.nirvana.archive.NirvanaArchiveBot.go(NirvanaArchiveBot.java:197)
        at org.wikipedia.nirvana.BasicBot.startWithConfig(BasicBot.java:331)
        at org.wikipedia.nirvana.BasicBot.run(BasicBot.java:180)
        at org.wikipedia.nirvana.archive.NirvanaArchiveBot.main(NirvanaArchiveBot.java:71)

**Comment by Nirvanchik** [comment]
Done.
